// Supplier notifications for the Purchase Order workflow. Called FIRE-AND-FORGET from the PO service
// (the caller never awaits + swallows errors), so a failure here can NEVER roll back the PO state.
// The PO PDF — generated by the Document Platform — is the source of truth; the email body stays a
// short cover note. Skips cleanly when the supplier has no email.

import { getCompanyProfile, getRegionalSettings } from "#modules/settings/settings.service.js";
import { sendTemplatedEmail } from "#modules/email/email.service.js";
import { generatePurchaseOrderPdf } from "#modules/document/document.service.js";
import { formatDate, formatMoney } from "#modules/document/document.formatter.js";
import type { AuditActor } from "#modules/audit/audit.service.js";
import type { PurchaseOrderWithRelations } from "./purchase-order.repository.js";

// Email the supplier the issued PO with the generated PDF attached. Throws on a send failure so the
// fire-and-forget caller's `.catch` can log it (the PO stays `sent` regardless).
export async function notifySupplierPoSent(
  po: PurchaseOrderWithRelations,
  actor?: AuditActor,
): Promise<void> {
  const to = po.supplier?.contactEmail?.trim();
  if (!to) {
    console.info(`PO ${po.code}: supplier has no email — supplier notification skipped.`);
    return;
  }
  const [company, regional] = await Promise.all([getCompanyProfile(), getRegionalSettings()]);
  const pdf = await generatePurchaseOrderPdf(po, actor?.email ?? po.sentBy);
  await sendTemplatedEmail(
    "po.sent",
    to,
    {
      supplierName: po.supplier?.name ?? po.supplierName ?? "",
      contactPerson: po.supplier?.contactPerson ?? "",
      poCode: po.code,
      orderDate: formatDate(po.orderDate, regional.dateFormat, regional.timezone),
      expectedDeliveryDate: formatDate(po.expectedDeliveryDate, regional.dateFormat, regional.timezone),
      grandTotal: formatMoney(po.grandTotalPence, po.currency || "GBP"),
      companyLegalName: company.legalName,
    },
    { attachments: [{ filename: pdf.filename, content: pdf.buffer, contentType: pdf.mimeType }] },
  );
}

// Notify the supplier a PO was cancelled — ONLY when it had already been issued to them (`sentAt`
// set), so a draft/approved PO the supplier never received is never emailed. No attachment.
export async function notifySupplierPoCancelled(po: PurchaseOrderWithRelations): Promise<void> {
  const to = po.supplier?.contactEmail?.trim();
  if (!to || !po.sentAt) return;
  const company = await getCompanyProfile();
  await sendTemplatedEmail("po.cancelled", to, {
    supplierName: po.supplier?.name ?? po.supplierName ?? "",
    contactPerson: po.supplier?.contactPerson ?? "",
    poCode: po.code,
    companyLegalName: company.legalName,
  });
}
