// Supplier notifications for the Purchase Order workflow. Called FIRE-AND-FORGET from the PO service
// (the caller never awaits + swallows errors), so a failure here can NEVER roll back the PO state.
// The PO PDF — generated by the Document Platform — is the source of truth; the email body stays a
// short cover note. Skips cleanly when the supplier has no email.

import { getCompanyProfile, getRegionalSettings } from "#modules/settings/settings.service.js";
import { sendTemplatedEmail } from "#modules/email/email.service.js";
import { generatePurchaseOrderPdf } from "#modules/document/document.service.js";
import { formatDate, formatMoney } from "#modules/document/document.formatter.js";
import * as userRepo from "#modules/user/user.repository.js";
import type { AuditActor } from "#modules/audit/audit.service.js";
import type { PurchaseOrderWithRelations } from "./purchase-order.repository.js";

// Email the supplier the issued PO with the generated PDF attached. Throws on a send failure so the
// fire-and-forget caller's `.catch` can log it (the PO stays `sent` regardless).
export async function notifySupplierPoSent(
  po: PurchaseOrderWithRelations,
  actor?: AuditActor,
): Promise<void> {
  const to = po.supplier?.contactEmail?.trim();
  if (!to) {
    console.info(`PO ${po.code}: supplier has no email — supplier notification skipped.`);
    return;
  }
  const [company, regional] = await Promise.all([getCompanyProfile(), getRegionalSettings()]);
  const pdf = await generatePurchaseOrderPdf(po, actor?.email ?? po.sentBy);
  await sendTemplatedEmail(
    "po.sent",
    to,
    {
      supplierName: po.supplier?.name ?? po.supplierName ?? "",
      contactPerson: po.supplier?.contactPerson ?? "",
      poCode: po.code,
      orderDate: formatDate(po.orderDate, regional.dateFormat, regional.timezone),
      expectedDeliveryDate: formatDate(po.expectedDeliveryDate, regional.dateFormat, regional.timezone),
      grandTotal: formatMoney(po.grandTotalPence, po.currency || "GBP"),
      companyLegalName: company.legalName,
    },
    { attachments: [{ filename: pdf.filename, content: pdf.buffer, contentType: pdf.mimeType }] },
  );
}

// Notify the staff who can approve a PO that one has been submitted for their decision.
// FIRE-AND-FORGET from the PO service. Recipients are active staff whose role grants
// `purchase_orders.approve` (or full access "*"); the submitter is excluded (no self-nudge).
// Each approver is emailed individually so one bad address never blocks the rest.
export async function notifyApproversPoSubmitted(
  po: PurchaseOrderWithRelations,
  submittedByEmail: string | null,
): Promise<void> {
  const approvers = (await userRepo.findActiveWithRole()).filter((u) => {
    const perms = u.role?.permissions ?? [];
    const canApprove = perms.includes("purchase_orders.approve") || perms.includes("*");
    return canApprove && u.email !== submittedByEmail;
  });
  if (approvers.length === 0) {
    console.info(`PO ${po.code}: no approvers to notify.`);
    return;
  }
  const vars = {
    poCode: po.code,
    supplierName: po.supplier?.name ?? po.supplierName ?? "",
    grandTotal: formatMoney(po.grandTotalPence, po.currency || "GBP"),
    submittedBy: submittedByEmail ?? "",
  };
  await Promise.all(
    approvers.map((a) =>
      sendTemplatedEmail("po.submitted", a.email, { ...vars, approverName: a.firstName }).catch((e) =>
        console.error(
          `PO ${po.code} approval email to ${a.email} failed:`,
          e instanceof Error ? e.message : e,
        ),
      ),
    ),
  );
}

// Notify the assigned Project Manager a PO has been routed to them for review + send.
// FIRE-AND-FORGET from the PO service. Skips cleanly when no PM email is on the order.
export async function notifyPmAssigned(po: PurchaseOrderWithRelations): Promise<void> {
  const to = po.pmEmail?.trim();
  if (!to) {
    console.info(`PO ${po.code}: no PM email — assignment notification skipped.`);
    return;
  }
  const regional = await getRegionalSettings();
  await sendTemplatedEmail("po.pm_assigned", to, {
    pmName: po.pmName ?? "",
    poCode: po.code,
    supplierName: po.supplier?.name ?? po.supplierName ?? "",
    grandTotal: formatMoney(po.grandTotalPence, po.currency || "GBP"),
    expectedDeliveryDate: formatDate(po.expectedDeliveryDate, regional.dateFormat, regional.timezone),
    assignedBy: po.pmAssignedBy ?? "",
  });
}

// Notify the supplier a PO was cancelled — ONLY when it had already been issued to them (`sentAt`
// set), so a draft/approved PO the supplier never received is never emailed. No attachment.
export async function notifySupplierPoCancelled(po: PurchaseOrderWithRelations): Promise<void> {
  const to = po.supplier?.contactEmail?.trim();
  if (!to || !po.sentAt) return;
  const company = await getCompanyProfile();
  await sendTemplatedEmail("po.cancelled", to, {
    supplierName: po.supplier?.name ?? po.supplierName ?? "",
    contactPerson: po.supplier?.contactPerson ?? "",
    poCode: po.code,
    companyLegalName: company.legalName,
  });
}
